bn_core_homepage:
    path:     /
    defaults:
        _controller: BNCoreBundle:Default:index

bn_core_contact:
    path:    /contact
    defaults:
        _controller: BNCoreBundle:Default:contact

